"turn on syntax highlighting
syntax on

"basic configurations
set tabstop=4
set shiftwidth=4
set softtabstop=4
set cindent shiftwidth=4
set autoindent
set number
set background=dark

"recursive map in insert and command modes
map! jj <esc>

