export OS=$(uname)
export HN=$(hostname -s)

export LANG=en_US.UTF-8
export LC_ALL=$LANG
export EDITOR=/usr/bin/vi

export PS1=''
export PS1=$PS1'[${USER}][${HOSTNAME}]'
export PS1=$PS1'[$(date +%Y-%m-%d)][$(date +%H:%M:%S)]'
export PS1=$PS1'[$PWD]'

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
export LSCOLORS=exfxcxdxbxegedabagacad

export READLINE_MODE=vi
export READLINE_MODE=emacs
set -o $READLINE_MODE

export HISTTIMEFORMAT='%F %T  '
export HISTCONTROL=ignoredups
export HISTSIZE=5000

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias gs='git status'
alias ga='git add *'
alias gc='git commit'

export APPLICATIONS=$HOME/Applications
export APPLICATIONS_BIN=$APPLICATIONS/bin
export LOCALPATH=$LOCALPATH:$APPLICATIONS:$APPLICATIONS_BIN

alias cdbin='cd $APPLICATIONS_BIN'
alias resync='synchronize'
alias reload='source $HOME/.bash_profile'
alias hosts='cat /etc/hosts'

alias l='ls $LS_OPTIONS -hl'
alias ll='ls $LS_OPTIONS -hlA'

alias cdp='cd $HOME/Programming'
alias cds='cd $HOME/Sources'
alias cdr='cd $HOME/Resumes'
alias cdj='cd $HOME/Jobs'
alias cdd='cd $HOME/Downloads'

export ACE_HOME=$HOME/Sources/ace
if [ $HN == 'liying' ]; then export ACE_HOME=$HOME/orc/ace; fi
export ACE_ROOT=$ACE_HOME/wrappers
export ACE_LIB=$ACE_ROOT/lib
export LOCAL_DYLD_LIBRARY_PATH=$ACE_LIB:$LOCAL_DYLD_LIBRARY_PATH

export BOOST_HOME=$HOME/Sources/boost
if [ $HN == 'liying' ]; then export BOOST_HOME=$HOME/Programming/boost; fi
export BOOST_INCLUDE=$BOOST_HOME/include
export BOOST_LIBRARY=$BOOST_HOME/lib
export LOCAL_DYLD_LIBRARY_PATH=$BOOST_LIBRARY:$LOCAL_DYLD_LIBRARY_PATH

export QUANTLIB_HOME=$HOME/Sourses/quantlib
if [ $HN == 'liying' ]; then export QUANTLIB_HOME=$HOME/Courses/HKU/COMP7406_FIN3/quantlib; fi
export QUANTLIB_INCLUDE=$QUANTLIB_HOME/include
export QUANTLIB_LIBRARY=$QUANTLIB_HOME/lib
export LOCAL_DYLD_LIBRARY_PATH=$QUANTLIB_LIBRARY:$LOCAL_DYLD_LIBRARY_PATH

alias cdace='cd $ACE_ROOT'
alias cdboost='cd $BOOST_HOME'
alias cdquant='cd $QUANTLIB_HOME'


export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export JAVA_LIB=$JAVA_HOME/lib
export JAVA=$JAVA_HOME/bin
export CLASSPATH=$JAVA_LIB:$CLASSPATH
export LOCALPATH=$LOCALPATH:$JAVA

export JRE_HOME=$JAVA_HOME/jre
export JRE_LIB=$JRE_HOME/lib
export JRE=$JRE_HOME/bin
export CLASSPATH=$JRE_LIB:$CLASSPATH
export LOCALPATH=$LOCALPATH:$JRE

export M2_HOME=/opt/apache-maven-3.2.1
export M2=$M2_HOME/bin
export LOCALPATH=$LOCALPATH:$M2


export MASTER_HOME=$HOME/MasterProject
export NESOX_HOME=$MASTER_HOME/Nesox
export NESOX_BIN=$NESOX_HOME/bin
export LOCALPATH=$LOCALPATH:$NESOX_BIN
export CLUSTERSCRIPT=$MASTER_HOME/ClusterScripts
export LOCALPATH=$LOCALPATH:$CLUSTERSCRIPT

alias cdmaster='cd $MASTER_HOME'
alias cdnesox='cd $NESOX_HOME'


export ALGO_HOME=$HOME/Programming/algo
export ALGO_INCLUDE=$ALGO_HOME/incl
export ALGO_LIBRARY=$ALGO_HOME/libs


export PROD_HOME=$HOME/productivity
export MAKE_HOME=$PROD_HOME/make
export MT_HOME=$PROD_HOME/magictrace

alias cdprod='cd $PROD_HOME'
alias cpmk='cp $MAKE_HOME/Makefile.mk ./Makefile'
alias lnmk='ln -s $MAKE_HOME/Makefile.mk ./Makefile'
alias cpmktex='cp $MAKE_HOME/MakefileTeX.mk ./Makefile'
alias lnmktex='ln -s $MAKE_HOME/MakefileTeX.mk ./Makefile'
alias cptex='cp $PROD_HOME/Tex/*.tex ./'
alias cpdox='cp $PROD_HOME/doxygen/doxygen.config ./'
alias cpmt='cp $MT_HOME/mt* ./'

export CODEBASE_HOME=$HOME/CodeBase
alias cdcb='cd $CODEBASE_HOME'

export TB_HOME=$HOME/Sources/tbricks
export TB_HOME=$HOME/Tbricks/tbricks.tb

alias cdtb='cd $TB_HOME'

export TB_OS_TYPE=i386-apple-darwin
export TB_TC_HOME=$TB_HOME/toolchain
export TB_TC_PATH=$TB_TC_HOME/$TB_OS_TYPE/bin
export LOCALPATH=$LOCALPATH:$TB_TC_PATH

export TB_GW_HOME=$TB_HOME/src/servers/connectivity
export TB_LB_HOME=$TB_HOME/src/libraries

alias cdgw='cd $TB_GW_HOME'
alias cdmd='cd $TB_LB_HOME/market_data'
alias cdtr='cd $TB_LB_HOME/trading'
alias cdtemp='cd $HOME/Tbricks/tbricks.master/src/servers/connectivity/template'
alias cdfema='cd $TB_GW_HOME/cffex/fema/src'
alias cdfemalib='cd $TB_LB_HOME/transport_fema'

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$LOCAL_DYLD_LIBRARY_PATH
export PATH=$PATH:$LOCALPATH

function helloworld() { echo "Bash: Hello, World!"; } 
function synchronize()
{
    progname=$1
    if [ "$progname" == "bash" ] || [ "$progname" == "" ]; then
        command cp $HOME/.bash_profile $HOME/.bash_profile.bk
        command cp $PROD_HOME/bash/bashrc $HOME/.bash_profile
    elif [ "$progname" == "tmux" ]; then
        command cp $HOME/.tmux.conf $HOME/.tmux.conf.bk
        command cp $PROD_HOME/tmux/tmux.conf $HOME/.tmux.conf
    elif [ "$progname" == "vim" ]; then
        command cp $HOME/.vimrc $HOME/.vimrc.bk
        command cp $PROD_HOME/vim/vimrc $HOME/.vimrc
    fi
}

WELCOME="Readline:[mode=$READLINE_MODE]! Load Bash Profile Successed!"
COMMENT="echo some string in login shell may cause rsync or ssh not work"

