export LANG=en_US.UTF-8
export LC_ALL=$LANG
export EDITOR=/usr/bin/vi

export PS1=$PS1'[${USER}][${HOSTNAME}]'
export PS1=''
export PS1=$PS1'[$(date +%Y-%m-%d)][$(date +%H:%M:%S)]'
export PS1=$PS1'[$PWD]'

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
export LSCOLORS=ExGxBxDxCxEgEdxbxgxcxd
export LSCOLORS=exfxcxdxbxegedabagacad

export READLINE_MODE=vi
export READLINE_MODE=emacs
set -o $READLINE_MODE

export APPLICATIONS=$HOME/Applications
export LOCALPATH=$LOCALPATH:$APPLICATIONS

alias resync='synchronize'
alias reload='source $HOME/.bash_profile'
alias hosts='cat /etc/hosts'

alias l='ls $LS_OPTIONS -hl'
alias ll='ls $LS_OPTIONS -hlA'

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

alias cdp='cd $HOME/Programming'
alias cds='cd $HOME/Sources'
alias cdr='cd $HOME/Resumes'
alias cdj='cd $HOME/Jobs'


export ACE_HOME=$HOME/orc/ace
export ACE_ROOT=$ACE_HOME/wrappers
export ACE_LIB=$ACE_ROOT/lib
export LOCAL_DYLD_LIBRARY_PATH=$ACE_LIB:$LOCAL_DYLD_LIBRARY_PATH

export BOOST_HOME=$HOME/Programming/boost
export BOOST_INCLUDE=$BOOST_HOME/include
export BOOST_LIBRARY=$BOOST_HOME/lib
export LOCAL_DYLD_LIBRARY_PATH=$BOOST_LIBRARY:$LOCAL_DYLD_LIBRARY_PATH

export QUANTLIB_HOME=$HOME/Courses/HKU/comp7406/quantlib
export QUANTLIB_INCLUDE=$QUANTLIB_HOME/include
export QUANTLIB_LIBRARY=$QUANTLIB_HOME/lib

alias cdace='cd $ACE_ROOT'
alias cdboost='cd $BOOST_HOME'
alias cdquant='cd $QUANTLIB_HOME'


export JAVA_HOME=`/usr/libexec/java_home`
export JAVA_LIB=$JAVA_HOME/lib
export JAVA=$JAVA_HOME/bin
export CLASSPATH=$JAVA_LIB:$CLASSPATH
export LOCALPATH=$LOCALPATH:$JAVA

export JRE_HOME=$JAVA_HOME/jre
export JRE_LIB=$JRE_HOME/lib
export JRE=$JRE_HOME/bin
export CLASSPATH=$JRE_LIB:$CLASSPATH
export LOCALPATH=$LOCALPATH:$JRE

export M2_HOME=/opt/apache-maven-3.2.1
export M2=$M2_HOME/bin
export LOCALPATH=$LOCALPATH:$M2


export MASTER_HOME=$HOME/MasterProject
export NESOX_HOME=$MASTER_HOME/Nesox
export NESOX_BIN=$NESOX_HOME/bin
export LOCALPATH=$LOCALPATH:$NESOX_BIN
export CLUSTERSCRIPT=$MASTER_HOME/ClusterScripts
export LOCALPATH=$LOCALPATH:$CLUSTERSCRIPT

alias cdmaster='cd $MASTER_HOME'
alias cdnesox='cd $NESOX_HOME'


export ALGO_HOME=$HOME/Programming/algo
export ALGO_INCLUDE=$ALGO_HOME/incl
export ALGO_LIBRARY=$ALGO_HOME/libs


export PROD_HOME=$HOME/Productivity
export MAKE_HOME=$PROD_HOME/Make

alias cdprod='cd $PROD_HOME'
alias cpmk='cp $MAKE_HOME/Makefile.mk ./'
alias lnmk='ln -s $MAKE_HOME/Makefile.mk ./Makefile'
alias cpmktex='cp $MAKE_HOME/MakefileTeX.mk ./Makefile'
alias lnmktex='ln -s $MAKE_HOME/MakefileTeX.mk ./Makefile'
alias cptex='cp $PROD_HOME/Tex/*.tex ./'


export TB_HOME=$HOME/Sources/tb
export GW_HOME=$TB_HOME/src/servers/connectivity/

alias cdtb='cd $TB_HOME'
alias cdgw='cd $GW_HOME'

export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$LOCAL_DYLD_LIBRARY_PATH
export PATH=$PATH:$LOCALPATH

function helloworld() { echo "Bash: Hello, World!"; } 
function synchronize()
{
command cp $PROD_HOME/Bash/bashrc $HOME/.bash_profile
}

WELCOME="Readline:[mode=$READLINE_MODE]! Load Bash Profile Successed!"
echo $WELCOME

